### ISSUE TITLE
"Not a valid binary file" when running GSA on samples provided

### ISSUE THREAD

**Issue by iJustinCabral** [michaelbrownuc/GadgetSetAnalyzer#11]
Hey there,

I'm a graduate student working with hardening binaries for a project and came across your tool. I have all the correct dependencies installed however when I run the sample command given in the GitHub I come across this error:

![InkedAnnotation 2022-06-16 133101_LI](https://user-images.githubusercontent.com/1973054/174133827-aabcde34-56b8-4699-8c68-241b4b7b0132.jpg)

I also looked at the logs (as well ass --output_console) from the analysis for the original binary and they don't seem to have gadgets found. 

<img width="391" alt="Annotation 2022-06-16 133953" src="https://user-images.githubusercontent.com/1973054/174132919-bd9491c1-1d81-44c3-bd07-9b5b4457c0d6.png">

I've run ROPgadget separately on the sample binaries provided (both original & reduced) and the tool works fine for finding + reporting the amount of gadgets found. 

Any idea on why this is error may be occuring? Thank you.

**Comment by michaelbrownuc** [comment]
As for why there are no gadgets in the logs, this is probably because there was an error in the readme. The filename for the base binary should be `date-8.21.origin`, not `date-8.21`.

**Comment by michaelbrownuc** [comment]
As for the error message, I think that's coming from angr, try removing the --output_addresses flag and see it that's the problem.

**Comment by iJustinCabral** [comment]
Inside the folders each non-reduced binary uses .origin :
<img width="289" alt="Annotation 2022-06-16 151212" src="https://user-images.githubusercontent.com/1973054/174147343-2cb613a2-2f98-44a7-8696-7288e4c5ee42.png">

However I did two runs, one with your recommended change and the other with .orgin, as well as removed --output_addresses. While it no longer gave the message of invalid binary, the counts coming back from the logs are blank. 

<img width="463" alt="Annotation 2022-06-16 151800" src="https://user-images.githubusercontent.com/1973054/174148175-fbdf8e16-4c8f-4a26-9634-6005f207f30e.png">

With output_console on:

<img width="335" alt="Annotation 2022-06-16 152057" src="https://user-images.githubusercontent.com/1973054/174148579-d319e241-6a8f-4e76-9021-880c6ed29b50.png">

I've tested all the binaries provided in /samples with ROPgadget so I know they're valid but for some reason the tool doesn't want to seem analyze correctly. 

Any other ideas on why this could be? Thank you

**Comment by michaelbrownuc** [comment]
What command are you using with ROPgadget?  GSA uses:

`ROPgadget --binary <your_target> --all --multibr`

Try this and see if your invocations of ROPgadget still work.


It might also be useful to make sure the binaries from the repo were fetched correctly.  Do they run?

**Comment by iJustinCabral** [comment]
For ROPgadget I normally just run --binary and --ropchain but I did a run with both of your suggested flags and it still works as normally intended. 
<img width="395" alt="Annotation 2022-06-21 070450" src="https://user-images.githubusercontent.com/1973054/174785104-1b806d1e-3b59-436b-b2e1-ad5f7aa17f8d.png">

I've also tested each of the binaries to make sure that they run as intended. The "origin binaries" seem to run just fine, as well as the "reduced binaries". I provided some examples below using mkdir and rm. 

<img width="395" alt="Annotation 2022-06-21 071034" src="https://user-images.githubusercontent.com/1973054/174786646-63dbd2ba-50c9-4427-bff6-063124dca65c.png">

<img width="397" alt="Annotation 2022-06-21 071420" src="https://user-images.githubusercontent.com/1973054/174786669-6e4a4a39-cd7a-46c8-9bbf-292a0255a46a.png">


And this is the output with GSA when analyzing the mkdir sample binaries:

<img width="396" alt="Annotation 2022-06-21 071815" src="https://user-images.githubusercontent.com/1973054/174787334-2e3f4d56-45ac-4a87-8176-91a7f641e5d0.png">

For my GSA set up, I'm using a docker container which pulls the angr framework, then I install ROPgadget and clone the GSA repository to the container. ROPgadget as you can see works fine, but perhaps there's something happening with the angr framework that's having an effect on the GSA.py script? 

I'm pretty stumped on this. Thanks for the continued help trouble shooting.

**Comment by michaelbrownuc** [comment]
When GSA shows output like this, it is typically the result of an error running ROPgadget under the hood. To diagnose further, we will need to see exactly what GSA is getting when it runs ROPgadget in your environment.

Please add `print(output)` at line 182 of GadgetSet.py. Then re-run the tool and tell me what the output looks like.

**Comment by iJustinCabral** [comment]
Ok so I placed print(output) on line 182 :
<img width="452" alt="Annotation 2022-06-21 104006" src="https://user-images.githubusercontent.com/1973054/174827821-b4da2915-7079-4a74-8bba-66aa980c3e1b.png">

But got this error: **NameError; name 'output' is not defined**
<img width="348" alt="Annotation 2022-06-21 104057" src="https://user-images.githubusercontent.com/1973054/174827902-7c79ab21-7ebc-46c6-b9eb-e77a0e6585ff.png">

**Comment by iJustinCabral** [comment]
Ok so I added print(output) to line 182 in GadgetSet.py:
<img width="344" alt="Annotation 2022-06-21 110314" src="https://user-images.githubusercontent.com/1973054/174832900-84457a37-f6f6-4157-93c1-2a7d4c6e4747.png">

And the error I got was **Can't open the binary or binary not found** : 
<img width="383" alt="Annotation 2022-06-21 105916" src="https://user-images.githubusercontent.com/1973054/174832191-e36fbd08-bca8-48c5-9302-1f5ada6be0fb.png">

So it looks like even though removing --output_addresses removed the initial error from earlier, there still seems to be an error with analyzing the reduced binary.

**Comment by iJustinCabral** [comment]
Solved the problem. It looks like there was just a missing . in order to move the directory up one place before analyzing the binaries. 

So the correct statement was : 

python3 GSA.py --output_metrics --output_addresses **..**/samples/CHISEL/date/date-8.21.origin "{'Aggressive':'**..**/samples/CHISEL/date/date-8.21.reduced'}"
<img width="356" alt="Annotation 2022-06-21 110736" src="https://user-images.githubusercontent.com/1973054/174833864-aaaea2ba-2714-4e6e-b630-e4982e500f56.png">


Thank you for all the help with the trouble shooting. Looking forward to using this tool for my work.

**Comment by michaelbrownuc** [comment]
Glad you figured out the issue. I've updated the README to fix the error.  Thanks!
