### ISSUE TITLE
Created Docker Container

### ISSUE THREAD

**Issue by iJustinCabral** [michaelbrownuc/GadgetSetAnalyzer#12]
Hey Michael,

I've gone ahead and Dockerized the GSA in a public docker hub repository with the dependencies needed for ease of use.

Feel free to pull my image and and copy it to create your own for use on this repository.

Docker image name is **ijustincabral/gsa** on docker hub

To run it and then copy it for your own image do:
```
docker run -it ijustincabral/gsa:beta
```

Upon running, it will take users directly into the GSA/src folder which will allow them to simply copy and paste the provided sample command to see the results.

Thanks again for the awesome tool.

**Comment by michaelbrownuc** [comment]
Very cool! Thanks for your contribution.
